<a href="https://colab.research.google.com/github/Lakshyagupta5532/Number-Guessing_Game-python-/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Customer Dataset Analysis

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('IPL.csv')
df.head()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
0,1,"March 26,2022","Wankhede Stadium, Mumbai",Chennai,Kolkata,Group,Kolkata,Field,131,5,133,4,Kolkata,Wickets,6,Umesh Yadav,MS Dhoni,50,Dwayne Bravo,3--20
1,2,"March 27,2022","Brabourne Stadium, Mumbai",Delhi,Mumbai,Group,Delhi,Field,177,5,179,6,Delhi,Wickets,4,Kuldeep Yadav,Ishan Kishan,81,Kuldeep Yadav,3--18
2,3,"March 27,2022","Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Group,Punjab,Field,205,2,208,5,Punjab,Wickets,5,Odean Smith,Faf du Plessis,88,Mohammed Siraj,2--59
3,4,"March 28,2022","Wankhede Stadium, Mumbai",Gujarat,Lucknow,Group,Gujarat,Field,158,6,161,5,Gujarat,Wickets,5,Mohammed Shami,Deepak Hooda,55,Mohammed Shami,3--25
4,5,"March 29,2022","Maharashtra Cricket Association Stadium,Pune",Hyderabad,Rajasthan,Group,Hyderabad,Field,210,6,149,7,Rajasthan,Runs,61,Sanju Samson,Aiden Markram,57,Yuzvendra Chahal,3--22

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             74 non-null     int64
 1   date                 74 non-null     object
 2   venue                74 non-null     object
 3   team1                74 non-null     object
 4   team2                74 non-null     object
 5   stage                74 non-null     object
 6   toss_winner          74 non-null     object
 7   toss_decision        74 non-null     object
 8   first_ings_score     74 non-null     int64
 9   first_ings_wkts      74 non-null     int64
 10  second_ings_score    74 non-null     int64
 11  second_ings_wkts     74 non-null     int64
 12  match_winner         74 non-null     object
 13  won_by               74 non-null     object
 14  margin               74 non-null     int64
 15  player_of_the_match  74 non-null     object
 16  top_scorer           74 non-null     object
 17  highscore            74 non-null     int64
 18  best_bowling         74 non-null     object
 19  best_bowling_figure  74 non-null     object
dtypes: int64(7), object(13)
memory usage: 11.7+ KB

In [ ]:
df.isnull().sum()
#zero null values

match_id               0
date                   0
venue                  0
team1                  0
team2                  0
stage                  0
toss_winner            0
toss_decision          0
first_ings_score       0
first_ings_wkts        0
second_ings_score      0
second_ings_wkts       0
match_winner           0
won_by                 0
margin                 0
player_of_the_match    0
top_scorer             0
highscore              0
best_bowling           0
best_bowling_figure    0
dtype: int64

In [ ]:
#Ques1 -  find the total number of matches in df?
df.shape[0]

74

In [ ]:
#ques2 - How many unique venues hosted matches in IPL?
df['venue'].nunique()

6

In [ ]:
#Ques3 - Which team won thw most matches?
# df['match_winner'].value_counts().head(1)
df['match_winner'].value_counts().idxmax()

'Gujarat'

In [ ]:
#Ques4 - How many matches were won by the team that won the toss?
df[df['match_winner'] == df['toss_winner']].shape[0]

36

In [ ]:
#Ques5 - Which venue hosted the most matches?
df['venue'].value_counts().idxmax()

'Wankhede Stadium, Mumbai'

In [ ]:
#Ques6 - What is the avg first inning score in IPL 2025?
# sumOfFirstInningScore = df['first_ings_score'].sum()
# sumOfFirstInningScore/df.shape[0]
df['first_ings_score'].mean()

np.float64(171.1216216216216)

In [ ]:
#Ques7 - How many matches had a first innings score greater than 200?
(df['first_ings_score'] > 200).sum()

np.int64(13)

In [ ]:
#Ques8 - Which venue has the highest avg first inning score?
df.head(1)
df.groupby('venue')['first_ings_score'].mean().idxmax()

'Eden Gardens, Kolkata'

In [ ]:
#Ques9 - Find the avg first inng score for each venue?
df.groupby('venue')['first_ings_score'].mean()

venue
Brabourne Stadium, Mumbai                       177.250000
Dr DY Patil Sports Academy, Mumbai              170.700000
Eden Gardens, Kolkata                           197.500000
Maharashtra Cricket Association Stadium,Pune    171.461538
Narendra Modi Stadium, Ahmedabad                143.500000
Wankhede Stadium, Mumbai                        166.761905
Name: first_ings_score, dtype: float64

In [ ]:
#Ques10 - Which team has the highest avg first ing score when they are team1?
df.groupby('team1')['first_ings_score'].mean().idxmax()

'Punjab'

In [ ]:
#Ques11 - Find the persentage of matches where the toss winner also won the match
TMW = (df['toss_winner'] == df['match_winner']).sum()
persentage = TMW/df.shape[0]
persentage*100

np.float64(48.64864864864865)

In [ ]:
#Ques12 - Which team won the toss most of the time?
df['toss_winner'].value_counts().idxmax()

'Hyderabad'

In [ ]:
#Ques13- Which venue has hosted the most matches won by CSK?
df[df['match_winner'] == 'Chennai'].value_counts('venue').idxmax()

'Dr DY Patil Sports Academy, Mumbai'

In [ ]:
#Ques14 - Which team won most matches by runs?
n = df[df['won_by'] == 'Runs']
n.groupby('match_winner').size().idxmax()

'Lucknow'

In [ ]:
#Ques15 - Which team has the highest avg winning margin when winning by runs
n = df[df['won_by'] == 'Runs']
n.groupby('match_winner')['margin'].mean().idxmax()

'Kolkata'

In [ ]:
#Ques16 - Add a new column as High_scoring_match (1 if first_ings_score > 200 otherwise 0)
df['High_scoring_match'] = (df['first_ings_score']>200).astype(int)
#New col create as last col in DataFrame
df.sample(1)

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,High_scoring_match
57,58,"May 11,2022","Dr DY Patil Sports Academy, Mumbai",Delhi,Rajasthan,Group,Delhi,Field,160,6,...,2,Delhi,Wickets,8,Mitchell Marsh,Mitchell Marsh,89,Chetan Sakariya,2--23,0

In [ ]:
#Ques16 - Number of matches played by each team?
df['team1'].value_counts() + df['team2'].value_counts()
df['match_winner'].value_counts()

match_winner
Gujarat      12
Rajasthan    10
Banglore      9
Lucknow       9
Punjab        7
Delhi         7
Kolkata       6
Hyderabad     6
Chennai       4
Mumbai        4
Name: count, dtype: int64

In [ ]:
#Ques17 - Which Team has the highest win persentage?
matchPlayed = pd.concat([df['team1'],df['team2']]).value_counts()
matchWinner = df['match_winner'].value_counts()
((matchWinner/matchPlayed)*100).idxmax()

'Gujarat'

In [ ]:
#Ques18 - Which team performs best while chasing?
n = df[df['won_by'] == 'Wickets']
q = n.groupby('match_winner').size().idxmax()
q

'Gujarat'

In [ ]:
#Ques19 - Which venue has the highest avg first inning score?
df.groupby('venue')['first_ings_score'].mean().idxmax()

'Eden Gardens, Kolkata'

In [ ]:
#Ques20 - Which team has most player of the match award?

#Ans - We doesnot know that the player which got player of the match award belong to which team
#      so we doesnot assume this without knowing.

In [ ]:
#Ques21 - Which Player won the Most Player of the Match awards?
df['player_of_the_match'].value_counts().idxmax()

'Kuldeep Yadav'

In [ ]:
#Ques22 - Is the toss winner got the advantage or not?
#OR
#Ques22 - percentage of tosswinner == matchwinner?
n = df[df['toss_winner'] == df['match_winner']].shape[0]
percentage = n/df.shape[0]
percentage*100

48.64864864864865

In [ ]:
#Ques23 -